### ISSUE TITLE
Making this plot looks nicer

### ISSUE THREAD

**Issue by nTavakoli** [nTavakoli/Assignment2#1]
Hello,
The only issue that I have is changing the title of each subplot from numeric values (1,2,..,12) to string (the name of each month).
Thank you

**Comment by pdirmeyer** [comment]
There are many ways to accomplish this. Consider that you have the panels numbered with the value of `month` (1 through 12), which you could use as an index of a list of names of the months.

**Comment by nTavakoli** [comment]
I used the following code to change the title of each subplot from numeric values to string (the name of each month):

ds_sm['month']=['January', 'February', 'March', 'April', 'May', 'June', 'July', 'August', 'September', 'October', 'November', 'December']

**Comment by pdirmeyer** [comment]
This looks good - you may close this issue.
