### ISSUE TITLE
Assignment 2: Spatial domain of plot

### ISSUE THREAD

**Issue by pdirmeyer** [nTavakoli/Assignment2#3]
Since you are plotting soil moisture, which is only over ice-free land, there are two improvements you can make to the domain of the plot:

1. You can crop out Antarctica by limiting the latitudes to [-60:90].
2. The longitude where there is no land outside Antarctica is through the Bering Sea between Alaska and Siberia. That longitude is around 169˚W. You have already inserted the cyclic_point in longitude, so you could shift your plot to be centered at 11˚E, spanning longitudes from -169 to 191. This range is ideal for displaying data over the continents.

**Comment by nTavakoli** [comment]
1. I did this part in CDO, but by using .sel and slice we can select the arbitrary domain.
2. I shifted my plot to 11 E by using "{'projection': ccrs.PlateCarree(central_longitude=-11)}" and also changing the spanning longitudes by using "np.arange(-169,191,90), crs=ccrs.PlateCarree()".
