### ISSUE TITLE
Assignment 2: LaTeX formatting

### ISSUE THREAD

**Issue by pdirmeyer** [nTavakoli/Assignment2#4]
In the label for your colorbar, the units are not well formatted. You can insert LaTeX-style formatted text in any plotted strings by enclosing that text between `$`. With this, you can create superscripts for the dimensions "meters cubed". See: https://matplotlib.org/stable/tutorials/text/mathtext.html for basic examples in matplotlib, and  https://en.wikibooks.org/wiki/LaTeX/Mathematics for a complete guide to LaTeX formatting.

**Comment by nTavakoli** [comment]
I revised the unit by using "label='[$m^{3}\;m^{-3}$]'".
